### ISSUE TITLE
cannot load on macOS(High Sierra)

### ISSUE THREAD

**Issue by hiroki802** [borodust/trivial-gamekit#16]
[package bodge-sndfile]...........................
..........
Read error between positions 3476 and 3595 in /Users/noguchihiroki/quicklisp/dists/org.borodust.bodge/software/bodge-sndfile-20171121230741/main.lisp.
> Error: Reader error: No external symbol named "READ-STREAM-CONTENT-INTO-BYTE-VECTOR" in package #<Package "ALEXANDRIA.0.DEV"> .

**Comment by borodust** [comment]
Most likely, you need to update `alexandria` system to to the latest version. Do you have it in `~/quicklisp/local-projects/`? If not, please, run:

```lisp
(ql:update-all-dists)
```
and try loading `trivial-gamekit` again.

**Comment by hiroki802** [comment]
Thank you for your advice.
I tried compiling on roswell, and I could load the system.
Now there are some other issues:
[package trivial-gamekit]...........
(:TRIVIAL-GAMEKIT)
? (gamekit:defgame example () ())
#<STANDARD-METHOD TRIVIAL-GAMEKIT::CONFIGURE-GAME (EXAMPLE)>
? (defmethod gamekit:draw ((this example))
  (gamekit:draw-text "Hello, Gamedev!" (gamekit:vec2 240.0 240.0)))
#<STANDARD-METHOD TRIVIAL-GAMEKIT:DRAW (EXAMPLE)>
? (gamekit:start 'example)
> Error: The value NIL is not of the expected type HASH-TABLE.
> While executing: GETHASH, in process pooled-executor-worker(93).


;;;
;;; #<PROCESS pooled-executor-worker(93) [Active] #x302002C353CD> requires access to Shared Terminal Input
;;; Type (:y 93) to yield control to this thread.
;;;
> Error: The value NIL is not of the expected type HASH-TABLE.
> While executing: GETHASH, in process pooled-executor-worker(92).


;;;
;;; #<PROCESS pooled-executor-worker(92) [Active] #x302002C3583D> requires access to Shared Terminal Input
;;; Type (:y 92) to yield control to this thread.
;;;

**Comment by hiroki802** [comment]
I changed the CL to SBCL on roswell, and it works.

**Comment by borodust** [comment]
Thank you for your report. Glad the problem was resolved.
`trivial-gamekit` [runs](https://borodust.org/projects/trivial-gamekit/#requirements) on `x86_64` `SBCL` and `CCL`  only yet.

**Comment by borodust** [comment]
Actually, tested it out a couple of moments ago on `CCL` (according to output you've provided, you were running this implementation), and indeed, there are some problems, so I'll leave this issue open until I resolve those `CCL` issues.

**Comment by borodust** [comment]
Actually, tested it out a couple of moments ago on CCL (according to output you've provided, you were running this implementation), and indeed, there are some problems. I'll make new issue.

**Comment by borodust** [comment]
Engine bug fixed. `CCL` should work now too.

**Comment by hiroki802** [comment]
I tried on CCL, but the situation was the same...

**Comment by borodust** [comment]
Hmm, that's strange. What is returned when you call
```lisp
(lisp-implementation-version)
```
with `CCL`

**Comment by borodust** [comment]
Ah, btw, don't forget to call 
```lisp
(ql:update-all-dists)
```
before running the example.

**Comment by hiroki802** [comment]
Thank you for your advice!
I updated all the dists, and tried again.
I also clear the .cash in home directory.
So far it's okay because I can run it on SBCL.

? (ql:quickload :trivial-gamekit)
[package bodge-sndfile]...........................
...........
Read error between positions 3476 and 3595 in /Users/noguchihiroki/quicklisp/dists/org.borodust.bodge/software/bodge-sndfile-20171121230741/main.lisp.
> Error: Reader error: No external symbol named "READ-STREAM-CONTENT-INTO-BYTE-VECTOR" in package #<Package "ALEXANDRIA.0.DEV"> .
> While executing: CCL::%PARSE-TOKEN, in process listener(1).
> Type :GO to continue, :POP to abort, :R for a list of available restarts.

**Comment by borodust** [comment]
Seems to be the same error: your `CCL` installation sees old `alexandria` system. Not sure how roswell handles it, but it is possible you need to run `(ql:update-all-dists)` when using `CCL` too.

**Comment by hiroki802** [comment]
Now I can run it on ccl.
What I did was ...
・delete the .cache in HOME directory, 
・install alexandria again.

**Comment by borodust** [comment]
Nice! Glad it all worked out well.
