### ISSUE TITLE
Antialiasing issue when drawing adjacent sprites with non-integer canvas translation values

### ISSUE THREAD

**Issue by defaultxr** [borodust/trivial-gamekit#27]
When the canvas is translated to non-integer values, seams appear between sprites that should be adjacent. Example of basic code to reproduce:
```lisp
(defmethod gamekit:draw ((this game))
  (gamekit:with-pushed-canvas ()
    (gamekit:translate-canvas 0.5 0.5)
    (gamekit:draw-image (gamekit:vec2 0 0) :tile)
    (gamekit:draw-image (gamekit:vec2 0 32) :tile)
    (gamekit:draw-image (gamekit:vec2 32 0) :tile)
    (gamekit:draw-image (gamekit:vec2 32 32) :tile)))
```

Where `:tile` can be any 32x32 image. Since these are all drawn next to each other, the resulting image should appear together, but instead the background seeps through between each tile. This seems most prominent when the canvas's translation is 0.5 away from an integer.

**Comment by borodust** [comment]
Thank you for the report! I'm back from a vacation and gonna look into that soon.

**Comment by borodust** [comment]
I managed to reproduce the issue, but unfortunately a couple of tricks didn't work out, so i need to seek help from `nanovg` (the underlying tech behind `trivial-gamekit` 2d abstraction) guyz.

As a workaround for now, you can `#'floor` values before passing them into `#'translate-canvas`. That works okish even for animated tiling.

**Comment by borodust** [comment]
Code I used for testing: https://gist.github.com/borodust/2de8d545f90ed035b308e873ab45a558

**Comment by borodust** [comment]
Related `nanovg` issue: https://github.com/memononen/nanovg/issues/487

**Comment by borodust** [comment]
Another workaround solution suggested by `nanovg` author - expanding image rectangle a bit: https://gist.github.com/borodust/36c03465a9e8798131e6796b4fbc378f

**Comment by borodust** [comment]
For the fix though, gonna look into MSAA solution instead of custom nanovg AA.

**Comment by borodust** [comment]
Example of using 4x MSAA instead of custom antialiasing: https://gist.github.com/borodust/26cb8f1be2801177f56d2358b2abff38
A bit slower, but no seams and no need to tinker with tiles.

Basically, provide `:samples 4` to `#'start` function
```lisp
(gamekit:start 'game :samples 4)
```
