### ISSUE TITLE
gamekit:stop does not work in a event handler

### ISSUE THREAD

**Issue by lthms** [borodust/trivial-gamekit#30]
Hi.

I am considering playing around with `trivial-gamekit`. Fair warning (and apologies in advance): I am very novice in common lisp.

I have been able to have a minimum working example (after installing quilcklisp).

I wanted to be able to quit the game from within the game, when for instance I press the left button of my mouse. Here is my code:

```common-lisp
(cl:in-package :lysk)

(gamekit:defgame example () ())

(defmethod gamekit:post-initialize ((app example))
  (gamekit:bind-button :mouse-left :released
                       (lambda () (gamekit:stop))))

(defun run ()
  (gamekit:start 'example))
```

Unfortunately, it does not work, and even worth I cannot use `gamekit:stop` from the repl after a pressed left button.

Could you help me a bit here? I have no idea how to do this.

Thanks by advance, for your help and for your work.

**Comment by borodust** [comment]
Hi! Thank you for the report. At the moment `#'stop` works synchronously which means when called from the event callback it actually blocks the engine. Let me fix that :)

**Comment by borodust** [comment]
Fixed in bodge dist.
```lisp
(ql:update-all-dists)
```

**Comment by borodust** [comment]
Please, let me know if it works fine for you after updating the dist.

**Comment by lthms** [comment]
Looks like it is working perfectly! Thanks a lot for your awesome reactivity. I will try to dive more into this, to see if I can implement a game client [for my 2D online game](https://github.com/lkn-org/lykan) using this project.

**Comment by borodust** [comment]
That would be awesome! Feel free to fire any issues or shoot any questions here or on `#lispgames`.
