### ISSUE TITLE
Randomish 1281 invalid value from viewports

### ISSUE THREAD

**Issue by arthev** [borodust/trivial-gamekit#34]
Gonna collect them here

OPENGL-ERROR: OpenGL signalled (1281 . INVALID-VALUE) from VIEWPORT.
   [Condition of type SIMPLE-CONDITION]

Restarts:
 0: [CONTINUE] Return from BREAK.
 1: [RERUN-FLOW-BLOCK] Rerun current flow block
 2: [SKIP-FLOW-BLOCK] Skip flow block returning nil
 3: [USE-FLOW-BLOCK-VALUE] Skip flow block returning provided value
 4: [ABORT] abort thread (#<THREAD "single-threaded-executor" RUNNING {100768A613}>)

Backtrace:
  0: (CL-OPENGL-BINDINGS:CHECK-ERROR #<unavailable argument>)
  1: ((:METHOD TRIVIAL-GAMEKIT:DRAW :AROUND (TRIVIAL-GAMEKIT:GAMEKIT-SYSTEM)) #<SNAKE-GAME:SNAKE-GAMEKIT {10076540D3}>) [fast-method]
      Locals:
        SB-PCL::.NEXT-METHOD-CALL. = #S(SB-PCL::FAST-METHOD-CALL ..)
        CL-BODGE.ENGINE:SYSTEM = #<SNAKE-GAME:SNAKE-GAMEKIT {10076540D3}>
  2: ((FLET "BODY-FU14" :IN TRIVIAL-GAMEKIT::%GAME-LOOP) #<unused argument>)
      [No Locals]
  3: (CL-FLOW::INVOKE-WITH-RESTARTS #<CLOSURE (FLET "BODY-FU14" :IN TRIVIAL-GAMEKIT::%GAME-LOOP) {100189887B}> NIL)
      Locals:
        ARG = NIL
        FU = #<CLOSURE (FLET "BODY-FU14" :IN TRIVIAL-GAMEKIT::%GAME-LOOP) {100189887B}>
        RESULT = NIL
  4: ((LABELS CL-FLOW::DISPATCHED :IN CL-FLOW::INVOKE-ATOMICALLY))
      [No Locals]
  5: ((FLET CL-BODGE.ENGINE::TRAPS-MASKING-TASK :IN BODGE-CONCURRENCY:DISPATCH))
      [No Locals]
  6: ((FLET CL-BODGE.GRAPHICS::RUN-TASK :IN BODGE-CONCURRENCY:DISPATCH))
      [No Locals]
  7: ((FLET CL-BODGE.ENGINE::INVOKER :IN BODGE-CONCURRENCY:DISPATCH))
      [No Locals]
  8: ((LAMBDA NIL :IN BODGE-CONCURRENCY::IGNITE))
      [No Locals]
  9: (DISSECT::STACK-TRUNCATOR #<CLOSURE DISSECT::WITH-TRUNCATED-STACK-LAMBDA {1001898CCB}>)
      Locals:
        FUNCTION = #<CLOSURE DISSECT::WITH-TRUNCATED-STACK-LAMBDA {1001898CCB}>
 10: (BODGE-UTIL::INVOKE-BODGY #<CLOSURE (LAMBDA NIL :IN BODGE-CONCURRENCY::IGNITE) {1001898C9B}>)
      Locals:
        FU = #<CLOSURE (LAMBDA () :IN BODGE-CONCURRENCY::IGNITE) {1001898C9B}>
 11: (BODGE-CONCURRENCY::IGNITE #<BODGE-CONCURRENCY::DISCARDING-EXECUTOR {100768A213}>)
      Locals:
        EXECUTOR = #<BODGE-CONCURRENCY::DISCARDING-EXECUTOR {100768A213}>
 12: ((LAMBDA NIL :IN INITIALIZE-INSTANCE))
      [No Locals]
 13: ((LAMBDA NIL :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS))
      [No Locals]
 14: ((FLET SB-UNIX::BODY :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
      Locals:
        SB-THREAD:THREAD = #<SB-THREAD:THREAD "single-threaded-executor" RUNNING {100768A613}>
      Catch-tags:
        SB-THREAD::%RETURN-FROM-THREAD
 15: ((FLET "WITHOUT-INTERRUPTS-BODY-4" :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
      Locals:
        SB-THREAD:THREAD = #<SB-THREAD:THREAD "single-threaded-executor" RUNNING {100768A613}>
 16: ((FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
      [No Locals]
      Catch-tags:
        SB-THREAD::%ABORT-THREAD
        SB-IMPL::%END-OF-THE-WORLD
        SB-INT:TOPLEVEL-CATCHER
 17: ((FLET "WITHOUT-INTERRUPTS-BODY-1" :IN SB-THREAD::CALL-WITH-MUTEX))
      Locals:
        GOT-IT = T
        MUTEX = #<SB-THREAD:MUTEX "thread result lock" owner: #<SB-THREAD:THREAD "single-threaded-executor" RUNNING {100768A613}>>
 18: (SB-THREAD::CALL-WITH-MUTEX #<CLOSURE (FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE) {7F532C52ECFB}> #<SB-THREAD:MUTEX "thread result lock" owner: #<SB-THREAD:THR..
      Locals:
        FUNCTION = #<CLOSURE (FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE) {7F532C52ECFB}>
        GOT-IT = T
        MUTEX = #<SB-THREAD:MUTEX "thread result lock" owner: #<SB-THREAD:THREAD "single-threaded-executor" RUNNING {100768A613}>>
        TIMEOUT = NIL
        VALUE = NIL
        WAITP = T
 19: (SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE #<SB-THREAD:THREAD "single-threaded-executor" RUNNING {100768A613}> NIL #<CLOSURE (LAMBDA NIL :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS) {100768A5BB..
      Locals:
        ARGUMENTS = NIL
        REAL-FUNCTION = #<CLOSURE (LAMBDA () :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS) {100768A5BB}>
        SETUP-SEM = NIL
        THREAD = #<SB-THREAD:THREAD "single-threaded-executor" RUNNING {100768A613}>
 20: ("foreign function: call_into_lisp")
 21: ("foreign function: new_thread_trampoline")
OPENGL-ERROR: OpenGL signalled (1281 . INVALID-VALUE) from VIEWPORT.
   [Condition of type SIMPLE-CONDITION]

Restarts:
 0: [CONTINUE] Return from BREAK.
 1: [RERUN-FLOW-BLOCK] Rerun current flow block
 2: [SKIP-FLOW-BLOCK] Skip flow block returning nil
 3: [USE-FLOW-BLOCK-VALUE] Skip flow block returning provided value
 4: [ABORT] abort thread (#<THREAD "single-threaded-executor" RUNNING {100768A613}>)

Backtrace:
  0: (CL-OPENGL-BINDINGS:CHECK-ERROR #<unavailable argument>)
  1: ((:METHOD TRIVIAL-GAMEKIT:DRAW :AROUND (TRIVIAL-GAMEKIT:GAMEKIT-SYSTEM)) #<SNAKE-GAME:SNAKE-GAMEKIT {10076540D3}>) [fast-method]
      Locals:
        SB-PCL::.NEXT-METHOD-CALL. = #S(SB-PCL::FAST-METHOD-CALL ..)
        CL-BODGE.ENGINE:SYSTEM = #<SNAKE-GAME:SNAKE-GAMEKIT {10076540D3}>
  2: ((FLET "BODY-FU14" :IN TRIVIAL-GAMEKIT::%GAME-LOOP) #<unused argument>)
      [No Locals]
  3: (CL-FLOW::INVOKE-WITH-RESTARTS #<CLOSURE (FLET "BODY-FU14" :IN TRIVIAL-GAMEKIT::%GAME-LOOP) {100189887B}> NIL)
      Locals:
        ARG = NIL
        FU = #<CLOSURE (FLET "BODY-FU14" :IN TRIVIAL-GAMEKIT::%GAME-LOOP) {100189887B}>
        RESULT = NIL
  4: ((LABELS CL-FLOW::DISPATCHED :IN CL-FLOW::INVOKE-ATOMICALLY))
      [No Locals]
  5: ((FLET CL-BODGE.ENGINE::TRAPS-MASKING-TASK :IN BODGE-CONCURRENCY:DISPATCH))
      [No Locals]
  6: ((FLET CL-BODGE.GRAPHICS::RUN-TASK :IN BODGE-CONCURRENCY:DISPATCH))
      [No Locals]
  7: ((FLET CL-BODGE.ENGINE::INVOKER :IN BODGE-CONCURRENCY:DISPATCH))
      [No Locals]
  8: ((LAMBDA NIL :IN BODGE-CONCURRENCY::IGNITE))
      [No Locals]
  9: (DISSECT::STACK-TRUNCATOR #<CLOSURE DISSECT::WITH-TRUNCATED-STACK-LAMBDA {1001898CCB}>)
      Locals:
        FUNCTION = #<CLOSURE DISSECT::WITH-TRUNCATED-STACK-LAMBDA {1001898CCB}>
 10: (BODGE-UTIL::INVOKE-BODGY #<CLOSURE (LAMBDA NIL :IN BODGE-CONCURRENCY::IGNITE) {1001898C9B}>)
      Locals:
        FU = #<CLOSURE (LAMBDA () :IN BODGE-CONCURRENCY::IGNITE) {1001898C9B}>
 11: (BODGE-CONCURRENCY::IGNITE #<BODGE-CONCURRENCY::DISCARDING-EXECUTOR {100768A213}>)
      Locals:
        EXECUTOR = #<BODGE-CONCURRENCY::DISCARDING-EXECUTOR {100768A213}>
 12: ((LAMBDA NIL :IN INITIALIZE-INSTANCE))
      [No Locals]
 13: ((LAMBDA NIL :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS))
      [No Locals]
 14: ((FLET SB-UNIX::BODY :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
      Locals:
        SB-THREAD:THREAD = #<SB-THREAD:THREAD "single-threaded-executor" RUNNING {100768A613}>
      Catch-tags:
        SB-THREAD::%RETURN-FROM-THREAD
 15: ((FLET "WITHOUT-INTERRUPTS-BODY-4" :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
      Locals:
        SB-THREAD:THREAD = #<SB-THREAD:THREAD "single-threaded-executor" RUNNING {100768A613}>
 16: ((FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
      [No Locals]
      Catch-tags:
        SB-THREAD::%ABORT-THREAD
        SB-IMPL::%END-OF-THE-WORLD
        SB-INT:TOPLEVEL-CATCHER
 17: ((FLET "WITHOUT-INTERRUPTS-BODY-1" :IN SB-THREAD::CALL-WITH-MUTEX))
      Locals:
        GOT-IT = T
        MUTEX = #<SB-THREAD:MUTEX "thread result lock" owner: #<SB-THREAD:THREAD "single-threaded-executor" RUNNING {100768A613}>>
 18: (SB-THREAD::CALL-WITH-MUTEX #<CLOSURE (FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE) {7F532C52ECFB}> #<SB-THREAD:MUTEX "thread result lock" owner: #<SB-THREAD:THR..
      Locals:
        FUNCTION = #<CLOSURE (FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE) {7F532C52ECFB}>
        GOT-IT = T
        MUTEX = #<SB-THREAD:MUTEX "thread result lock" owner: #<SB-THREAD:THREAD "single-threaded-executor" RUNNING {100768A613}>>
        TIMEOUT = NIL
        VALUE = NIL
        WAITP = T
 19: (SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE #<SB-THREAD:THREAD "single-threaded-executor" RUNNING {100768A613}> NIL #<CLOSURE (LAMBDA NIL :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS) {100768A5BB..
      Locals:
        ARGUMENTS = NIL
        REAL-FUNCTION = #<CLOSURE (LAMBDA () :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS) {100768A5BB}>
        SETUP-SEM = NIL
        THREAD = #<SB-THREAD:THREAD "single-threaded-executor" RUNNING {100768A613}>
 20: ("foreign function: call_into_lisp")
 21: ("foreign function: new_thread_trampoline")
OPENGL-ERROR: OpenGL signalled (1281 . INVALID-VALUE) from VIEWPORT.
   [Condition of type SIMPLE-CONDITION]

Restarts:
 0: [CONTINUE] Return from BREAK.
 1: [RERUN-FLOW-BLOCK] Rerun current flow block
 2: [SKIP-FLOW-BLOCK] Skip flow block returning nil
 3: [USE-FLOW-BLOCK-VALUE] Skip flow block returning provided value
 4: [ABORT] abort thread (#<THREAD "single-threaded-executor" RUNNING {100768A613}>)

Backtrace:
  0: (CL-OPENGL-BINDINGS:CHECK-ERROR #<unavailable argument>)
  1: ((:METHOD TRIVIAL-GAMEKIT:DRAW :AROUND (TRIVIAL-GAMEKIT:GAMEKIT-SYSTEM)) #<SNAKE-GAME:SNAKE-GAMEKIT {10076540D3}>) [fast-method]
      Locals:
        SB-PCL::.NEXT-METHOD-CALL. = #S(SB-PCL::FAST-METHOD-CALL ..)
        CL-BODGE.ENGINE:SYSTEM = #<SNAKE-GAME:SNAKE-GAMEKIT {10076540D3}>
  2: ((FLET "BODY-FU14" :IN TRIVIAL-GAMEKIT::%GAME-LOOP) #<unused argument>)
      [No Locals]
  3: (CL-FLOW::INVOKE-WITH-RESTARTS #<CLOSURE (FLET "BODY-FU14" :IN TRIVIAL-GAMEKIT::%GAME-LOOP) {100189887B}> NIL)
      Locals:
        ARG = NIL
        FU = #<CLOSURE (FLET "BODY-FU14" :IN TRIVIAL-GAMEKIT::%GAME-LOOP) {100189887B}>
        RESULT = NIL
  4: ((LABELS CL-FLOW::DISPATCHED :IN CL-FLOW::INVOKE-ATOMICALLY))
      [No Locals]
  5: ((FLET CL-BODGE.ENGINE::TRAPS-MASKING-TASK :IN BODGE-CONCURRENCY:DISPATCH))
      [No Locals]
  6: ((FLET CL-BODGE.GRAPHICS::RUN-TASK :IN BODGE-CONCURRENCY:DISPATCH))
      [No Locals]
  7: ((FLET CL-BODGE.ENGINE::INVOKER :IN BODGE-CONCURRENCY:DISPATCH))
      [No Locals]
  8: ((LAMBDA NIL :IN BODGE-CONCURRENCY::IGNITE))
      [No Locals]
  9: (DISSECT::STACK-TRUNCATOR #<CLOSURE DISSECT::WITH-TRUNCATED-STACK-LAMBDA {1001898CCB}>)
      Locals:
        FUNCTION = #<CLOSURE DISSECT::WITH-TRUNCATED-STACK-LAMBDA {1001898CCB}>
 10: (BODGE-UTIL::INVOKE-BODGY #<CLOSURE (LAMBDA NIL :IN BODGE-CONCURRENCY::IGNITE) {1001898C9B}>)
      Locals:
        FU = #<CLOSURE (LAMBDA () :IN BODGE-CONCURRENCY::IGNITE) {1001898C9B}>
 11: (BODGE-CONCURRENCY::IGNITE #<BODGE-CONCURRENCY::DISCARDING-EXECUTOR {100768A213}>)
      Locals:
        EXECUTOR = #<BODGE-CONCURRENCY::DISCARDING-EXECUTOR {100768A213}>
 12: ((LAMBDA NIL :IN INITIALIZE-INSTANCE))
      [No Locals]
 13: ((LAMBDA NIL :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS))
      [No Locals]
 14: ((FLET SB-UNIX::BODY :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
      Locals:
        SB-THREAD:THREAD = #<SB-THREAD:THREAD "single-threaded-executor" RUNNING {100768A613}>
      Catch-tags:
        SB-THREAD::%RETURN-FROM-THREAD
 15: ((FLET "WITHOUT-INTERRUPTS-BODY-4" :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
      Locals:
        SB-THREAD:THREAD = #<SB-THREAD:THREAD "single-threaded-executor" RUNNING {100768A613}>
 16: ((FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
      [No Locals]
      Catch-tags:
        SB-THREAD::%ABORT-THREAD
        SB-IMPL::%END-OF-THE-WORLD
        SB-INT:TOPLEVEL-CATCHER
 17: ((FLET "WITHOUT-INTERRUPTS-BODY-1" :IN SB-THREAD::CALL-WITH-MUTEX))
      Locals:
        GOT-IT = T
        MUTEX = #<SB-THREAD:MUTEX "thread result lock" owner: #<SB-THREAD:THREAD "single-threaded-executor" RUNNING {100768A613}>>
 18: (SB-THREAD::CALL-WITH-MUTEX #<CLOSURE (FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE) {7F532C52ECFB}> #<SB-THREAD:MUTEX "thread result lock" owner: #<SB-THREAD:THR..
      Locals:
        FUNCTION = #<CLOSURE (FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE) {7F532C52ECFB}>
        GOT-IT = T
        MUTEX = #<SB-THREAD:MUTEX "thread result lock" owner: #<SB-THREAD:THREAD "single-threaded-executor" RUNNING {100768A613}>>
        TIMEOUT = NIL
        VALUE = NIL
        WAITP = T
 19: (SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE #<SB-THREAD:THREAD "single-threaded-executor" RUNNING {100768A613}> NIL #<CLOSURE (LAMBDA NIL :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS) {100768A5BB..
      Locals:
        ARGUMENTS = NIL
        REAL-FUNCTION = #<CLOSURE (LAMBDA () :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS) {100768A5BB}>
        SETUP-SEM = NIL
        THREAD = #<SB-THREAD:THREAD "single-threaded-executor" RUNNING {100768A613}>
 20: ("foreign function: call_into_lisp")
 21: ("foreign function: new_thread_trampoline")

**Comment by borodust** [comment]
Well, for those kind of errors i need steps to reproduce them. Do you have a code around that spits those errors? During what process this often happens?

**Comment by borodust** [comment]
Looks like I've managed to reproduce the issue by just stopping and starting applications random number of times, so it is certainly smth is broken in `trivial-gamekit`. Gonna research that behavior.

**Comment by borodust** [comment]
Graphics system received quite a bit of updates and as of now I cannot reproduce the behavior anymore. If it still the case for you, please, reopen the issue.
