### ISSUE TITLE
Randomish freezes with window turning white

### ISSUE THREAD

**Issue by arthev** [borodust/trivial-gamekit#35]
*inferior-lisp* fills with the following stuff when it happens:

Error 00000502 after stroke fill 1
Error 00000502 after stroke fill 0
Error 00000502 after stroke fill 1
Error 00000502 after tex paint tex
Error 00000501 after convex fill
Error 00000502 after convex fill
Error 00000502 after convex fill
Error 00000502 after convex fill
Error 00000502 after convex fill
Error 00000502 after convex fill
Error 00000502 after stroke fill 0
Error 00000502 after stroke fill 1
Error 00000502 after stroke fill 0
Error 00000502 after stroke fill 1
Error 00000502 after tex paint tex
Error 00000501 after convex fill
Error 00000502 after convex fill
Error 00000502 after convex fill
Error 00000502 after convex fill
Error 00000502 after convex fill
Error 00000502 after convex fill
Error 00000502 after stroke fill 0
Error 00000502 after stroke fill 1
Error 00000502 after stroke fill 0
Error 00000502 after stroke fill 1
Error 00000502 after tex paint tex
Error 00000501 after convex fill
Error 00000502 after convex fill
Error 00000502 after convex fill
Error 00000502 after convex fill
Error 00000502 after convex fill
Error 00000502 after convex fill
Error 00000502 after stroke fill 0
Error 00000502 after stroke fill 1
Error 00000502 after stroke fill 0
Error 00000502 after stroke fill 1
Error 00000502 after tex paint tex
Error 00000501 after convex fill
Error 00000502 after convex fill
Error 00000502 after convex fill
Error 00000502 after convex fill
Error 00000502 after convex fill
Error 00000502 after convex fill
Error 00000502 after stroke fill 0
Error 00000502 after stroke fill 1
Error 00000502 after stroke fill 0
Error 00000502 after stroke fill 1
Error 00000502 after tex paint tex
Error 00000501 after convex fill
Error 00000502 after tex paint tex
Error 00000502 after tex paint tex
Error 00000502 after tex paint tex
Error 00000502 after tex paint tex
Error 00000501 after convex fill
Error 00000502 after tex paint tex
Error 00000502 after tex paint tex
Error 00000502 after tex paint tex
Error 00000502 after tex paint tex
Error 00000501 after convex fill
Error 00000502 after tex paint tex
Error 00000502 after tex paint tex
Error 00000502 after tex paint tex
Error 00000502 after tex paint tex
Error 00000501 after convex fill
Error 00000502 after tex paint tex
Error 00000502 after tex paint tex
Error 00000502 after tex paint tex
Error 00000502 after tex paint tex
Error 00000501 after convex fill
Error 00000502 after tex paint tex
Error 00000502 after tex paint tex
Error 00000502 after tex paint tex
Error 00000502 after tex paint tex
Error 00000501 after convex fill
Error 00000502 after tex paint tex
Error 00000502 after tex paint tex
Error 00000502 after tex paint tex
Error 00000502 after tex paint tex
Error 00000501 after convex fill
Error 00000502 after tex paint tex
Error 00000502 after tex paint tex
Error 00000502 after tex paint tex
Error 00000502 after tex paint tex
Error 00000501 after convex fill
Error 00000502 after tex paint tex
Error 00000502 after tex paint tex
Error 00000502 after tex paint tex
Error 00000502 after tex paint tex
Error 00000501 after convex fill
Error 00000502 after tex paint tex
Error 00000502 after tex paint tex
Error 00000502 after tex paint tex
Error 00000502 after tex paint tex
Error 00000501 after convex fill
Error 00000502 after tex paint tex
Error 00000502 after tex paint tex
Error 00000502 after tex paint tex
Error 00000502 after tex paint tex
Error 00000501 after convex fill
Error 00000502 after tex paint tex
Error 00000502 after tex paint tex
Error 00000502 after tex paint tex
Error 00000502 after tex paint tex
Error 00000501 after convex fill
Error 00000502 after tex paint tex
Error 00000502 after tex paint tex
Error 00000502 after tex paint tex
Error 00000502 after tex paint tex
Error 00000501 after convex fill
Error 00000502 after tex paint tex
Error 00000502 after tex paint tex
Error 00000502 after tex paint tex
Error 00000502 after tex paint tex
Error 00000501 after convex fill
Error 00000502 after tex paint tex
Error 00000502 after tex paint tex
Error 00000502 after tex paint tex
Error 00000502 after tex paint tex
Error 00000501 after convex fill
Error 00000502 after tex paint tex
Error 00000502 after tex paint tex
Error 00000502 after tex paint tex
Error 00000502 after tex paint tex
Error 00000501 after convex fill
Error 00000502 after tex paint tex
Error 00000502 after tex paint tex
Error 00000502 after tex paint tex
Error 00000502 after tex paint tex
Error 00000501 after convex fill
Error 00000502 after tex paint tex
Error 00000502 after tex paint tex
Error 00000502 after tex paint tex
Error 00000502 after tex paint tex
Error 00000501 after convex fill
Error 00000502 after tex paint tex
Error 00000502 after tex paint tex
Error 00000502 after tex paint tex
Error 00000502 after tex paint tex
Error 00000501 after convex fill
Error 00000502 after tex paint tex
Error 00000502 after tex paint tex
Error 00000502 after tex paint tex
Error 00000502 after tex paint tex
Error 00000501 after convex fill
Error 00000502 after tex paint tex
Error 00000502 after tex paint tex
Error 00000502 after tex paint tex
Error 00000502 after tex paint tex
Error 00000501 after convex fill

**Comment by borodust** [comment]
Interesting. Could you please provide minimal example that reproduces this behavior?

**Comment by borodust** [comment]
Actually, no need for an example. I think I've managed to reproduces this too. Looks like this is actually related to #34

**Comment by borodust** [comment]
Graphics system received quite a bit of updates and as of now I cannot reproduce the behavior anymore. If it still the case for you, please, reopen the issue.
