### ISSUE TITLE
Images get "stretched"

### ISSUE THREAD

**Issue by kahrkunne** [borodust/trivial-gamekit#37]
Since an image is worth 1000 words:
https://imgur.com/yqumwse
Top left is the window created by trivial-gamekit, bottom right is an image viewer showing the actual image. Both windows are 1280x720 and so is the image, yet trivial-gamekit "stretches" it (which makes it look unsharp and makes it not fit in the window). 

Here's my code:

```(ql:quickload :trivial-gamekit)

(defpackage :uvne
  (:use :cl :trivial-gamekit))

(defvar *width* 1280)
(defvar *height* 720)
(defparameter *images* '())

(gamekit:defgame vn () ()
  (:viewport-width *width*)
  (:viewport-height *height*)
  (:viewport-title "Test"))

(defun draw-images ()
  (loop for img in *images* do
    (let ((img (car img))
          (pos (cadr img)))
      (gamekit:draw-image pos img))))

(defun add-image (pos img)
  (setq *images* (cons (list pos img) *images*)))

(defmethod gamekit:draw ((app vn))
  (draw-images))

(defun debug-start ()
  (progn
    (gamekit:start 'vn)
    (gamekit:bind-button :q :pressed (lambda () (gamekit:stop)))))
(defun debug-stop () (gamekit:stop))

;;; Test Section
(gamekit:register-resource-package :keyword "test/res/")
(gamekit:define-image :bg3 "bg3.png")
(add-image :bg3 (gamekit:vec2 0 0))

```

**Comment by borodust** [comment]
Rather than stretched it looks like it just doesn't fit (blue blocks are missing), which is interesting nevertheless. Are you using HiDPI display?

**Comment by kahrkunne** [comment]
The image is stretched first, then it attempts to fit it into the 720p window - which now doesn't fit, of course.
Yes, my screen is higher DPI than the "usual" 96 (I believe it's around 107 or so).

**Comment by borodust** [comment]
This might be related to mishandling of DPI. Work on good HiDPI-support is still in-progress. I've pushed an update which allows to disable "best-guess" autoscaling for unexpected DPI in trivial-gamekit.
You are already using testing dist, so you just need to
```lisp
(ql:update-all-dists)
```
Add `(:autoscaled nil)` to your `defgame` and try again the example. Please, let me know if this helps.

**Comment by borodust** [comment]
Can you arrange a project with resources included somewhere (repo or archive is fine)?

As for `#'gamekit:stop` - woopsy, gonna fix.

**Comment by borodust** [comment]
Testing dist updated: `#'gamekit:stop` should work as expected now.

**Comment by kahrkunne** [comment]
Another thing: #'gamekit:draw-text complains about *font* being unbound in the testing dist. e.g.:

```
(gamekit:defgame test () ())
(gamekit:start 'test)
(gamekit:draw-text "test" (gamekit:vec2 0 0))
```
leads to
```Backtrace:
  0: (TRIVIAL-GAMEKIT:DRAW-TEXT "test" #<VEC2 0.0 0.0> :FILL-COLOR NIL :FONT NIL)
      Locals:
        #:.DEFAULTING-TEMP. = NIL
        #:.DEFAULTING-TEMP.#1 = NIL
        #:N-SUPPLIED-0 = 0
        #:N-SUPPLIED-1 = 0
        ORIGIN = #<VEC2 0.0 0.0>
        STRING = "test"
  1: (SB-INT:SIMPLE-EVAL-IN-LEXENV (TRIVIAL-GAMEKIT:DRAW-TEXT "test" (BODGE-MATH:VEC2 0 0)) #<NULL-LEXENV>)
      Locals:
        SB-KERNEL:LEXENV = #<NULL-LEXENV>
        SB-IMPL::ORIGINAL-EXP = (TRIVIAL-GAMEKIT:DRAW-TEXT "test" (BODGE-MATH:VEC2 0 0))
  2: (EVAL (TRIVIAL-GAMEKIT:DRAW-TEXT "test" (BODGE-MATH:VEC2 0 0)))
      Locals:
        SB-IMPL::ORIGINAL-EXP = (TRIVIAL-GAMEKIT:DRAW-TEXT "test" (BODGE-MATH:VEC2 0 0))```

**Comment by borodust** [comment]
Draw routines can be used inside `#'draw` method only. See https://borodust.org/projects/trivial-gamekit/manual/#drawing

**Comment by kahrkunne** [comment]
Ah I see, thanks. My bad I guess.

**Comment by borodust** [comment]
Confirmed it was DPI-related issue. Fixed `:autoscaled` option - should work properly now. Testing dist updated.

**Comment by kahrkunne** [comment]
Can confirm the issue is fixed now! Thanks very much!

**Comment by borodust** [comment]
Thanks for the report!

**Comment by kahrkunne** [comment]
Fairly sure your fix now breaks accurately getting the mouse position:
```
(ql:quickload :trivial-gamekit)
(gamekit:defgame test () ()
  (:viewport-width 1280)
  (:viewport-height 720))
(defun start-test ()
  (gamekit:start 'test)
  (gamekit:bind-cursor
   (lambda (x y)
     (print x)
     (print y))))
```
Even hovering the mouse over the upper right corner, i.e. the one with the highest possible coordinates, which should be (1279, 719), only prints values going up to about (1012, 569)

**Comment by borodust** [comment]
I'll look into it.

**Comment by borodust** [comment]
Now instead of specifying `:autoscaled` option in `defgame` you need to pass it to `#'start`:
```lisp
(gamekit:start 'vn :autoscaled nil)
```
Testing dist updated.
