### ISSUE TITLE
Crash in Portacle macOS environment

### ISSUE THREAD

**Issue by borodust** [borodust/trivial-gamekit#4]
https://gist.github.com/zacharycarter/c79cccd5b3395d98c880d22286955a5a

**Comment by z3t0** [comment]
also happening to me

**Comment by borodust** [comment]
Does it work for you on bare x86_64 sbcl (e.g. the one from homebrew or AMD64 version from official website)?

**Comment by z3t0** [comment]
@borodust No it doesn't. I'm using homebrew's sbcl. I have seen this floating error with a lot of other libraries. ccl64 seemed to have worked for other libraries so I'll give  that a try.

**Comment by borodust** [comment]
@z3t0 Got it. I'll try to fix this as soon as I get my hands back to macOS machine in a couple of days or so. Thanks for the info!

**Comment by borodust** [comment]
I've fixed quite a few issues lately, including the ones with macOS. @z3t0 Can you check if it works for you these days? You can try out `hello-gamekit` project as a test case.

**Comment by borodust** [comment]
If you still have the problem, feel free to reopen the issue
