### ISSUE TITLE
How to set framerate

### ISSUE THREAD

**Issue by mdbergmann** [borodust/trivial-gamekit#42]
Hi.

This is just an inquiry. I didn't find any mention on it in the users manual.
I'm not such an irc user and asking this via Twitter seemed awkward.

I'd like to know if it is possible to set the framerate at which #'act/#'draw is called and the screen updated?

Cheers

**Comment by borodust** [comment]
Unfortunately, there's no way to set a framerate in `gamekit` yet. By default it is bound to monitor's refresh rate (v-sync enabled). I've got a few requests for setting custom framerate, so I'm gonna add this feature sooner or later.
So far your options would be:
* Decouple logic from framerate and bind it to a timeline instead - simulate a game world by a variable delta time each frame.
* Start another thread that handles logic in a loop with rate you need and push updates for rendering data into main thread via `#'gamekit:push-action` and use it data to render a world.

**Comment by borodust** [comment]
Or, for jam's sake, you can assume that every monitor has refresh rate of 60Hz and user systems support v-sync, and build a jam game with 60 logic steps per second :)

**Comment by mdbergmann** [comment]
ok, thanks.
So I guess this inquiry goes as a vote to implement frame rate. :)

**Comment by borodust** [comment]
Yup. Let's keep the issue open till this feature is implemented.

**Comment by borodust** [comment]
This is done. If you are using testing dist, `(ql:update-all-dists)` should bring you this feature.
See `:draw-rate` and `:act-rate` usage below:
```lisp
(gamekit:defgame hello-gamekit () ()
  (:viewport-width *canvas-width*)
  (:viewport-height *canvas-height*)
  (:viewport-title "Hello Gamekit!")
  (:draw-rate 60) ; for custom framerate in FPS
  (:act-rate 120)) ; for custom logic rate in #'act calls per second
```

**Comment by mdbergmann** [comment]
Great stuff. Thanks.
