### ISSUE TITLE
Screen scale keyword option

### ISSUE THREAD

**Issue by RyanBurnside** [borodust/trivial-gamekit#43]
**Issue**
Pixel art centric games often need a whole number scale to maintain detail and intent of the sprite artist. Resolutions like 320x200 need to be rendered at a higher resolution, a scale of 4x for example makes them comfortable for both artist and viewer. The resulting image should remain sharp and crisp with no interpolation.

**Suggested Resolution**:
Allow a screen resolution scale multiplier keyword to be specified. If fullscreen becomes supported, maintain the aspect ratio and draw black border bars as necessary.

**Comment by borodust** [comment]
Hm-m, I've looked into this thoroughly, but looks like `gamekit` won't support this option. It's possible to do in `cl-bodge`. I'll have another look at it and probably will make an example how to do that with `cl-bodge`. Basically, the idea is to render canvas into low-res texture and then blit it onto the screen with nearest interpolation.

**Comment by borodust** [comment]
Alright, this is sorta implemented via [`trivial-gamekit-postproc`](https://github.com/borodust/trivial-gamekit-postproc) system. You can specify indirect buffer width/height there, which is essentially kinda downsamples canvas to required resolution.

**Comment by borodust** [comment]
To align indirect buffer coordinates with canvas coordinates used in `draw-*` functions you can now specify `:canvas-width` and `:canvas-height` options of `defgame`.
