### ISSUE TITLE
act/draw called twice per frame

### ISSUE THREAD

**Issue by mdbergmann** [borodust/trivial-gamekit#46]
Hi.
I'm not sure if I'm doing something wrong, so this is more an inquiry.

I have set `draw-rate` and `act-rate` both to 2 (fps).

In my code I have a global variable that has a state to be drawn.
The state is drawn in `draw` and modified in `act`.

When I start the 'game' I see that act/draw is called twice in succession. However, with having set both to 2 fps I'd expect that draw and act is called in rotation.

```
CL-GOL/SRC/GAME-VISU> (gamekit:start 'gol-visu)
act...
draw...
; No values
draw...
act...
act...
draw...
draw...
...
```

**Comment by borodust** [comment]
This is an interesting observation. As for cause, no, those are correctly called once a frame, but the order wasn't preserved due to how custom rates were implemented. This is fixed in https://github.com/borodust/cl-bodge/commit/8806acc16b847579ea37541a7614413b77c3559b
Fix is in testing dist.

**Comment by mdbergmann** [comment]
Both, draw and act seem to be decoupled since it's possible to specify different frequencies.
So when act is 3 fps and draw is 2 fps I'm not sure if it would be possible at all to make act called before draw.
So I think it would be fine if they would be not related to each other when a model initialization can be done in `post-initialize`.
But I still would have expected to a sequence of:
```
act...
draw...
act...
draw...
...
```
Or am I wrong?

**Comment by borodust** [comment]
Yes. Those are decoupled indeed, but for simple case when rates are the same, I think it makes a bit of sense for them to be kinda consistent.
