### ISSUE TITLE
Fullscreen Support

### ISSUE THREAD

**Issue by itmuckel** [borodust/trivial-gamekit#47]
Is there a way to run the game full screen?

**Comment by borodust** [comment]
Yes. Supply `t` to `:fullscreen-p` option of `defgame`.

**Comment by itmuckel** [comment]
That creates a bug: Using the example from https://github.com/borodust/hello-gamekit the cursor offset is wrong.

I have a native resolution of 3840x2160 and the game resolution is defined as 1920x1080. Now, when I click in the lower left area the snakes head is bound almost correctly to the cursor position, but the more I wander to the upper right part of the screen the snake's head is too far up and right of the mouse cursor.

Example:
Assuming that (0, 0) is the lower left corner of my screen and (3480, 2160) the upper right.

Clicking (0, 0) is showing the head at (0, 0).
Clicking (0, 1080) is showing the head at (0, 2160).
Clicking (1920, 0) is showing the head at (3480, 0).
Clicking (960, 540) is showing the head at (1740, 1080).
Exceeding (1920, 1080) will draw the snake's head outside of the visible area.

Must I manually transform the received values from `gamekit:bind-cursor` or is this a bug? I think there was a difference between desktop fullscreen and real full screen.

**Comment by borodust** [comment]
Looks like a bug. I'll have a look.

**Comment by borodust** [comment]
[Fix](https://github.com/borodust/cl-bodge/commit/2a451f66705334c91d0141c4aaae39a2e5e267c4) is in testing dist. Install it with 
```common-lisp
(ql-dist:install-dist "http://bodge.borodust.org/dist/org.borodust.bodge.testing.txt")
```

**Comment by itmuckel** [comment]
Same behavior as before with small differences.

Now I actually checked what resolution I get, I just assumed that it was my desktop resolution of 3480x2160.

On the stable dist I get a resolution of 2560x1600.
On the testing dist (with the fix) I get 1024x768.

Just in case something is wrong with my code:

```lisp
(ql:quickload :trivial-gamekit)

(defvar *canvas-width* 1920)
(defvar *canvas-height* 1080)

(gamekit:register-resource-package :keyword "./")
(gamekit:define-image :snake-head "snake-head.png")
(gamekit:define-sound :snake-grab "snake-grab.ogg")

(gamekit:defgame hello-gamekit () ()
  (:viewport-width *canvas-width*)
  (:viewport-height *canvas-height*)
  (:viewport-title "Hello Gamekit!")
  (:fullscreen-p t))

(defvar *black* (gamekit:vec4 0 0 0 1))
(defvar *curve* (make-array 4 :initial-contents (list (gamekit:vec2 300 300)
						      (gamekit:vec2 375 300)
						      (gamekit:vec2 425 300)
						      (gamekit:vec2 500 300))))
(defvar *cursor-position* (gamekit:vec2 0 0))
(defvar *head-grabbed-p* nil)

(defmethod gamekit:post-initialize ((app hello-gamekit))
  (gamekit:bind-cursor (lambda (x y)
			 "When left mouse button is pressed, update snake's head position"
			 (when *head-grabbed-p*
			   (let ((head-position (aref *curve* 3)))
			     (setf (gamekit:x head-position) x
				   (gamekit:y head-position) y)))))

  (gamekit:bind-button :mouse-left :pressed
		       (lambda ()
			 (gamekit:play :snake-grab)
			 (setf *head-grabbed-p* t)))

  (gamekit:bind-button :mouse-left :released
		       (lambda () (setf *head-grabbed-p* nil))))

(defun real-time-seconds ()
  "Return seconds since certain point of time"
  (/ (get-internal-real-time) internal-time-units-per-second))

(defun update-position (position time)
  "Update position vector depending on the time supplied"
  (let* ((subsecond (nth-value 1 (truncate time)))
	 (angle (* 2 pi subsecond)))
    (setf (gamekit:y position) (+ 300 (* 100 (sin angle))))))

(defmethod gamekit:act ((app hello-gamekit))
  (update-position (aref *curve* 1) (real-time-seconds))
  (update-position (aref *curve* 2) (+ 0.3 (real-time-seconds))))

(defmethod gamekit:draw ((app hello-gamekit))
  (gamekit:draw-text "A snake that is!" (gamekit:vec2 300 400))
  (gamekit:draw-curve (aref *curve* 0)
		      (aref *curve* 3)
		      (aref *curve* 1)
		      (aref *curve* 2)
		      *black*
		      :thickness 5.0)
  (let ((head-image-position (gamekit:subt (aref *curve* 3) (gamekit:vec2 32 32))))
    (gamekit:draw-image head-image-position :snake-head)))

(gamekit:start 'hello-gamekit)
```

I use SBCL 1.4.14 (x86-64) for Windows 10 (64bit) combined with slime.
My Graphics Card is an NVIDIA GeForce GTX 1050 Ti.

**Comment by borodust** [comment]
I see. Looks like I misunderstood the question. So you want gamekit to set fullscreen resolution to 1920x1080, correct?

**Comment by borodust** [comment]
Or do you want it to keep native resolution when switching to fullscreen mode?

**Comment by itmuckel** [comment]
Well, my game should support different resolutions and scale up and down accordingly. 

I'm quite new to common lisp and trivial-gamekit, so I don't know if I can set the origin-rect and destination-rect of images (like in sdl2) to achieve that. In the end I need to do my own calculations to scale the game depending on the resolution. But it should map the mouse cursor to the right part of the screen.

All in all, yes, I want gamekit to set fullscreen resolution to 1920x1080. It should behave in fullscreen 1920x1080 the same as it would behave in windowed 1080.

**Comment by borodust** [comment]
Looks like autoscaling (HIDPI support) is borked. On it.

**Comment by borodust** [comment]
Alright, I figured out the problem. Fix is in testing dist.

Apparently, Windows (or maybe GLFW on Windows) doesn't allow us to create windows bigger than certain size and if we provide too big of a size it would just cut it down to max allowed - gamekit didn't know of that crap and used provided values as a viewport size and that broke autoscaling because native viewport (window) size was different from gamekit's. Now gamekit uses native size with gotcha being that `:viewport-width` and `:viewport-height` options are just a suggested size.

How to workaround that in gamekit:
* You can disable autoscaling at all by passing `:autoscaled nil` to `gamekit:start` and manage or not all that platform-dependent hidpi crap manually
* You can retrieve actual viewport size with `#'viewport-width` and `#'viewport-height` and scale canvas with `#'scale-canvas` in `#'draw` to accomodate this behavior
* Or you can ensure canvas size with `:canvas-width` and `:canvas-height` options of `defgame` and scale cursor and other viewport-related coordinates accordingly.

**Comment by itmuckel** [comment]
Alright then, I'll have a look later. I don't think this is too much of an issue for me, because I need to calculate some stuff anyway. Thank you very much for your support and quick help!

**Comment by borodust** [comment]
No probs! Thanks much for bringing that up.
