### ISSUE TITLE
How to properly stop a game

### ISSUE THREAD

**Issue by itmuckel** [borodust/trivial-gamekit#48]
When I call `(gamekit:stop)` like written in the docs and try to run my game again, I get the following error:

```
Engine already running
   [Condition of type SIMPLE-ERROR]

Restarts:
 0: [RETRY] Retry SLIME REPL evaluation request.
 1: [*ABORT] Return to SLIME's top level.
 2: [ABORT] abort thread (#<THREAD "new-repl-thread" RUNNING {1002CCD0A3}>)

Backtrace:
  0: (CL-BODGE.ENGINE:STARTUP (:ENGINE (:SYSTEMS (HELLO-GAMEKIT) :LOG-LEVEL :INFO) :HOST (:OPENGL-VERSION (3 3) :SAMPLES NIL :VIEWPORT-RESIZABLE NIL ...) :APPKIT (:ANTIALIASED T :SWAP-INTERVAL NIL)) :WORKI..
  1: (SB-INT:SIMPLE-EVAL-IN-LEXENV (TRIVIAL-GAMEKIT:START (QUOTE HELLO-GAMEKIT)) #<NULL-LEXENV>)
  2: (EVAL (TRIVIAL-GAMEKIT:START (QUOTE HELLO-GAMEKIT)))
  3: (SWANK::EVAL-REGION "(gamekit:start 'hello-gamekit) ..)
```

The funny thing is: This only happens on crashes.

When I exit my game by calling `(gamekit:stop)` out of `bind-button` it quits regularly. Are there corner cases where `(gamekit:stop)` doesn't clean up everything, for example the engine?

**Comment by borodust** [comment]
Yes. If you kill engine-specific threads by hitting `q` button randomly in a debugger - there's no way to properly recover engine state from that point - you would need to restart an image (`M-x s-r-i-lisp` in emacs). Use `continue` or `abort` restarts bound to `c` and `a` buttons accordingly if you are using Emacs. Or invoke those restarts from the debugger. Other useful restarts are `skip-flow-block` to try skipping broken code or `rerun-flow-block` to try evaluating it again (especially useful after fixing an error).

Btw, for a quick chat, you can find me in `#lispgames` IRC channel on freenode.net or in `#gamedev` channel on [lisp discord](https://discord.gg/Wf7f2pz) server. I'm often there, but If I'm not around other ppl that use gamekit might provide some insight.
