### ISSUE TITLE
a bug in mac catalina,  (gamekit:start 'example) can not start properly

### ISSUE THREAD

**Issue by mahaidong** [borodust/trivial-gamekit#51]
This is the screenshoot.
https://github.com/mahaidong/bugs/blob/master/readme.md

**Comment by borodust** [comment]
Not sure what's wrong with the screenshot. Window size?

**Comment by borodust** [comment]
Or, do you mean it hangs the REPL?

**Comment by mahaidong** [comment]
> Or, do you mean it hangs the REPL?

yeah,  it hangs the REPL.

**Comment by borodust** [comment]
Yes, this is expected. MacOSX requires all graphics-related work to be done in the main thread. Default SBCL REPL works in the main thread too. That leads to this behavior: once game loop grabs the main thread, default REPL won't work. As a workaround, you can create SWANK loop on non-main thread and connect to it with SLIME (or just use [SLIME](https://common-lisp.net/project/slime/) or [SLY](https://github.com/joaotavora/sly) from Emacs)
