### ISSUE TITLE
Component "bodge-blobs-support" not found, required by NIL

### ISSUE THREAD

**Issue by alexander982** [borodust/trivial-gamekit#55]
I am tried to install travial-gamekit like in [https://borodust.org/projects/trivial-gamekit/#installation-and-loading](url), but get:
`Component "bodge-blobs-support" not found, required by NIL
   [Condition of type ASDF/FIND-COMPONENT:MISSING-DEPENDENCY]

Restarts:
 0: [RETRY] Retry loading bodge-blobs-support.
 1: [RETRY] Retry EVAL of current toplevel form.
 2: [CONTINUE] Ignore error and continue loading file "/home/alexander/soft/portacle/all/quicklisp/dists/org.borodust.bodge/software/sndfile-blob-20191116131927/sndfile-blob.asd".
 3: [ABORT] Abort loading file "/home/alexander/soft/portacle/all/quicklisp/dists/org.borodust.bodge/software/sndfile-blob-20191116131927/sndfile-blob.asd".
 4: [RETRY] Retry #<DEFINE-OP > on #<UNDEFINED-SYSTEM "sndfile-blob">.
 5: [ACCEPT] Continue, treating #<DEFINE-OP > on #<UNDEFINED-SYSTEM "sndfile-blob"> as having been successful.
 --more--

Backtrace:
  0: (ASDF/FIND-COMPONENT:RESOLVE-DEPENDENCY-NAME NIL "bodge-blobs-support" NIL)
  1: ((LAMBDA NIL :IN ASDF/PARSE-DEFSYSTEM:REGISTER-SYSTEM-DEFINITION))
  2: (SB-INT:SIMPLE-EVAL-IN-LEXENV (ASDF/PARSE-DEFSYSTEM:DEFSYSTEM ASDF/USER::SNDFILE-BLOB :AUTHOR "Pavel Korolev" :DESCRIPTION "SNDFILE foreign library collection" ...) #<NULL-LEXENV>)
  3: (EVAL-TLF (ASDF/PARSE-DEFSYSTEM:DEFSYSTEM ASDF/USER::SNDFILE-BLOB :AUTHOR "Pavel Korolev" :DESCRIPTION "SNDFILE foreign library collection" ...) 0 NIL)
  4: ((LABELS SB-FASL::EVAL-FORM :IN SB-INT:LOAD-AS-SOURCE) (ASDF/PARSE-DEFSYSTEM:DEFSYSTEM ASDF/USER::SNDFILE-BLOB :AUTHOR "Pavel Korolev" :DESCRIPTION "SNDFILE foreign library collection" ...) 0)
  5: ((LAMBDA (SB-KERNEL:FORM &KEY :CURRENT-INDEX &ALLOW-OTHER-KEYS) :IN SB-INT:LOAD-AS-SOURCE) (ASDF/PARSE-DEFSYSTEM:DEFSYSTEM ASDF/USER::SNDFILE-BLOB :AUTHOR "Pavel Korolev" :DESCRIPTION "SNDFILE foreign..
  6: (SB-C::%DO-FORMS-FROM-INFO #<CLOSURE (LAMBDA (SB-KERNEL:FORM &KEY :CURRENT-INDEX &ALLOW-OTHER-KEYS) :IN SB-INT:LOAD-AS-SOURCE) {1003EECE8B}> #<SB-C::SOURCE-INFO {1003EECE43}> SB-C::INPUT-ERROR-IN-LOAD..
  7: (SB-INT:LOAD-AS-SOURCE #<SB-INT:FORM-TRACKING-STREAM for "file /home/alexander/soft/portacle/all/quicklisp/dists/org.borodust.bodge/software/sndfile-blob-20191116131927/sndfile-blob.asd" {1003EE97D3}>..
  8: ((FLET SB-FASL::THUNK :IN LOAD))
  9: (SB-FASL::CALL-WITH-LOAD-BINDINGS #<CLOSURE (FLET SB-FASL::THUNK :IN LOAD) {7FE603DAC47B}> #<SB-INT:FORM-TRACKING-STREAM for "file /home/alexander/soft/portacle/all/quicklisp/dists/org.borodust.bodge/..
 10: ((FLET SB-FASL::LOAD-STREAM :IN LOAD) #<SB-INT:FORM-TRACKING-STREAM for "file /home/alexander/soft/portacle/all/quicklisp/dists/org.borodust.bodge/software/sndfile-blob-20191116131927/sndfile-blob.asd..
 11: (LOAD #P"/home/alexander/soft/portacle/all/quicklisp/dists/org.borodust.bodge/software/sndfile-blob-20191116131927/sndfile-blob.asd" :VERBOSE NIL :PRINT NIL :IF-DOES-NOT-EXIST T :EXTERNAL-FORMAT :UTF-..
 12: (UIOP/UTILITY:CALL-WITH-MUFFLED-CONDITIONS #<CLOSURE (LAMBDA NIL :IN UIOP/LISP-BUILD:LOAD*) {1003ECD14B}> ("Overwriting already existing readtable ~S." #(#:FINALIZERS-OFF-WARNING :ASDF-FINALIZERS)))
 13: ((FLET "THUNK" :IN ASDF/ACTION:PERFORM))
 14: (SB-IMPL::%WITH-STANDARD-IO-SYNTAX #<CLOSURE (FLET "THUNK" :IN ASDF/ACTION:PERFORM) {7FE603DAC7CB}>)
 15: ((:METHOD ASDF/ACTION:PERFORM (ASDF/FIND-SYSTEM:DEFINE-OP ASDF/SYSTEM:SYSTEM)) #<ASDF/FIND-SYSTEM:DEFINE-OP > #<ASDF/SYSTEM:UNDEFINED-SYSTEM "sndfile-blob">) [fast-method]
 16: ((SB-PCL::EMF ASDF/ACTION:PERFORM) #<unused argument> #<unused argument> #<ASDF/FIND-SYSTEM:DEFINE-OP > #<ASDF/SYSTEM:UNDEFINED-SYSTEM "sndfile-blob">)
 17: ((LAMBDA NIL :IN ASDF/ACTION:CALL-WHILE-VISITING-ACTION))
 18: ((:METHOD ASDF/ACTION:PERFORM-WITH-RESTARTS :AROUND (T T)) #<ASDF/FIND-SYSTEM:DEFINE-OP > #<ASDF/SYSTEM:UNDEFINED-SYSTEM "sndfile-blob">) [fast-method]
 19: ((:METHOD ASDF/PLAN:PERFORM-PLAN (T)) #<ASDF/PLAN:SEQUENTIAL-PLAN {1003EC9E53}>) [fast-method]
 --more--
`
(ql:update-all-dists) don`t help.

**Comment by alexander982** [comment]
After `(ql:quickload :bodge-blobs-support)` command `(ql:quickload :trivial-gamekit)` works fine.

**Comment by borodust** [comment]
Can you please share your findings? What was the problem? This might help others to troubleshoot similar problems.

**Comment by borodust** [comment]
Ah, i see. Still weird though.
