### ISSUE TITLE
Error during distribution:deliver

### ISSUE THREAD

**Issue by mjgordon** [borodust/trivial-gamekit#56]
When running (trivial-gamekit.distribution:deliver), it always throws:
```
[Condition of type UIOP/RUN-PROGRAM:SUBPROCESS-ERROR]
```
with this backtrace:
```
0: (UIOP/RUN-PROGRAM::%CHECK-RESULT 1 :COMMAND ("/usr/bin/sbcl" "--script" "/home/matt/lisp/quicklisp/dists/org.borodust.bodge/software/cl-bodge-20200320210104/distribution/builder.lisp" "--output" "/hom..
  1: (UIOP/RUN-PROGRAM::%USE-LAUNCH-PROGRAM ("/usr/bin/sbcl" "--script" "/home/matt/lisp/quicklisp/dists/org.borodust.bodge/software/cl-bodge-20200320210104/distribution/builder.lisp" "--output" "/home/mat..
  2: ((FLET INFERIOR-SHELL::RUN-IT :IN INFERIOR-SHELL:RUN/NIL))
  3: (CL-BODGE.DISTRIBUTION:MAKE-DISTRIBUTION :TGK-DIST-TEST :BUILD-DIRECTORY NIL)
  4: (TRIVIAL-GAMEKIT.DISTRIBUTION:DELIVER :TGK-DIST-TEST EXAMPLE :BUILD-DIRECTORY NIL :ZIP NIL :LISP NIL)
  5: (SB-INT:SIMPLE-EVAL-IN-LEXENV (TRIVIAL-GAMEKIT.DISTRIBUTION:DELIVER :TGK-DIST-TEST (QUOTE EXAMPLE)) #<NULL-LEXENV>)
  6: (EVAL (TRIVIAL-GAMEKIT.DISTRIBUTION:DELIVER :TGK-DIST-TEST (QUOTE EXAMPLE)))
```

The REPL meanwhile prints what I assume is the output of that subprocess, which shows this error:
```
  Error finding package for symbol "WRITE-ASDF-MANIFEST-FILE":                                                                                                                                                                               
 The name "QUICKLISP-CLIENT" does not designate any package.                                                                                                                                                                                 
 ```
apparently stemming from the (generate-manifest) function in bodge's build.lisp file. 
Which is strange because adding e.g. ```(format t "~a~%" (describe 'ql:write-asdf-manifest-file))``` to the generate-manifest function works fine. 
I can also post more of that backtrace if necessary. 

I found this in my full-sized project, and confirmed it in a minimal project that just includes the hello-world code from the trivial-gamekit docs.

**Comment by borodust** [comment]
This is a strange error. Try running command (that is spilled in the backtrace) in a shell directly. Smth along the lines of
```sh
"/usr/bin/sbcl" "--script" "/home...
```
And let me know what the output is.

**Comment by borodust** [comment]
Actually, I probably see where the problem is going from. You might have `trivial-gamekit/distribution` as a dependency of your game - it shouldn't be.

**Comment by mjgordon** [comment]
Yes that's right, I had added the dependency into the .asd of my minimal test as well, removing it fixed it. Thanks!  

I'm curious though why asdf loading the distribution system when it loads the game system produces different results than just calling asdf:load-system for it at the REPL.

**Comment by borodust** [comment]
The problem is that `gamekit.distribution` uses quicklisp to gather some required information, but when actual building is happening there's no quicklisp present - only asdf is used. So if your game depends on `distribution` system, builder tries to load it but there's no quicklisp exists at this point.
