### ISSUE TITLE
is it possible to prevent clear screen at each redraw

### ISSUE THREAD

**Issue by Inc0ns1st3nt** [borodust/trivial-gamekit#58]
I disliked the idea of refreshing the screen at every draw.
Especially for simple programs like random walker, wouldn't it be much better if the program continuously draw, instead of keeping a list of objects drawn.

So is there a way to achieve this?

**Comment by Inc0ns1st3nt** [comment]
I had a look into the gamekit, but found nothing related. 
However, this function in cl-bodge seems promising.
```
(defun clear-rendering-output (output &key color)
  (%clear-rendering-output output (or color *default-clear-color*)))
```
But the way it is called in `draw-app` seems like it would be impossible to set its output arg to nil.

**Comment by Inc0ns1st3nt** [comment]
It seems handle-drawing is the method I am looking for, however, it doesn't seem to be called.
```
(defmethod handle-drawing ((this sketch) canvas ui)
  (format t "~a~%" this)
  (ge.gx:render t canvas :appkit-instance this)
  (ge.ui:compose-ui ui)
  t)
```

**Comment by Inc0ns1st3nt** [comment]
solved it.
```
(defmethod ge.app:handle-drawing ((this sketch) canvas ui)
  (format t "~a~%" this)
  (ge.gx:render t canvas :appkit-instance this)
  (ge.ui:compose-ui ui)
  t)
```
the method requires proper packaging naming

**Comment by borodust** [comment]
Just a warning: `cl-bodge` API is not finalized yet and is a subject to change (unlikely, but possibly). Use at your own risk.

Exposed `trivial-gamekit` API is rock-stable and won't _ever_ change. But yeah, there's no way to disable auto refresh using `gamekit` routines only.

**Comment by Inc0ns1st3nt** [comment]
Okay 👌 thanks for the heads up.
