### ISSUE TITLE
Crash when loading example

### ISSUE THREAD

**Issue by PaulAtTUBS** [borodust/trivial-gamekit#59]
Hello borodust,

I am very new to Common Lisp, so I may have made trivial mistakes.
When installing the gamekit according to the instructions and running the example, GLFW cannot be initialized.
I am running sbcl on Linux Subsystem (Ubuntu) on Windows 10.
I attached the entire log file, beginning with setting up quicklisp.

[trivial-gamekit-glfw-fail-log.txt](https://github.com/borodust/trivial-gamekit/files/4781512/trivial-gamekit-glfw-fail-log.txt)

**Comment by borodust** [comment]
Are you using `gamekit` within WSL? Maybe `cygwin`/`msys2`? Strangely, according to a log, it tries to use X11, meaning `SBCL` identified the system as `unix` Maybe you are using

**Comment by PaulAtTUBS** [comment]
Hello borodust,

thanks for your answer and I am sorry for the late reply.

> Are you using `gamekit `within WSL?
yes

> Maybe `cygwin`/`msys2`?
I tried to setup `cygwin` now but failed. I think the problem is that WSL cannot get a graphics context and needs an xserver for that (?). So I suppose this is neither an issue of `trivial-gamekit` or `sbcl` but setting up WSL with graphics capabilities correctly.

So thank you very much! :)
I will try the same on a real linux now to see if it works.

**Comment by borodust** [comment]
Just in case, gamekit should work in Windows environment too (not WSL, just plain Windows). All you need is Windows-native lisp implementation (e.g., SBCL or CCL for Windows).
