### ISSUE TITLE
System fails to load on sbcl + mac os x

### ISSUE THREAD

**Issue by can3p** [borodust/trivial-gamekit#6]
Here is a log: https://gist.github.com/can3p/b7b2470dc8129451b9d37f5ad9dcf84a

**Comment by borodust** [comment]
Thanks for reporting! 

This one is actually weird. Especially considering that I remember developing this wrapper for `ode` exactly on macOS machine. 

* Do you run x86_64 macos _and_ sbcl? 
* Do you have `cl-autowrap` somewhere `asdf` can find it? (`~/quicklisp/local-projects`)

Just in case, I would recommend running `(ql:update-all-dists)` and trying again.

**Comment by can3p** [comment]
* yes
* I installed this one with quicklisp, restarted the repl and tried to load the project - no luck there.

I also tried to update quicklisp dist and sbcl, and I'm still getting the same error, unfortunately

**Comment by borodust** [comment]
My apologies for the delay, I was in the middle of forking a library, required for `trivial-gamekit`. I've updated `bodge` dist, can you check if the problem still persist for you?

Don't forget to run
```lisp
(ql:update-all-dists)
```
first.
In case it fails with smth like 
```
The archive file "trivial-gamekit-20170909.tgz" for "trivial-gamekit" is
      the wrong size: expected 139,616, got 139,601
```
Try
```lisp
(ql:uninstall-dist "org.borodust.bodge")
(ql-dist:install-dist "http://bodge.borodust.org/dist/org.borodust.bodge.txt")
```

**Comment by borodust** [comment]
Tested it on colleague's machine with fresh sbcl install from homebrew. Works like charm! :D

Feel free to reopen the issue, if the problem is still there for you.

**Comment by can3p** [comment]
Works now, thanks!
