### ISSUE TITLE
game got error "arithmetic error DIVISION-BY-ZERO signalled" on Windows when minimizing the winow

### ISSUE THREAD

**Issue by leafbebop** [borodust/trivial-gamekit#60]
On Windows, OpenGL sends a change on viewport of (width, height) = (0, 0) to callback, and `cl-bodge.appkit:%update-canvas-and-ui-dimensions` handles it.

However, the expression 
https://github.com/borodust/cl-bodge/blob/fc65f3f8f646bf84e0b1e7a03cd03656888f211d/appkit/appkit.lisp#L115-L117

```
    (let* ((canvas-width (or this-canvas-width viewport-width))
           (canvas-height (or this-canvas-height viewport-height))
           (canvas-aspect (/ viewport-width canvas-width)))
```
is faulty. Due to the fact that `this-canvas-width` (which is slot `cl-bodge.appkit::canvas-width` of `this`, which is the game defined in `defgame`) is never set, `canvas-width` becomes `viewport-width`, which is the passed in width argument and defaulting `canvas-aspect` to 1... Except this time `viewport-width` is `0`, making it a `(/ 0 0)` error.

I noticed that there is another slot `trivial-gamekit:canvas-width` of the game, however I am not familiar enough to be certain whether the two slots should be merged or synchronized.

**Comment by borodust** [comment]
Thanks! Problem confirmed: gonna push a fix into the testing dist in a few hours.

**Comment by borodust** [comment]
Fix should be in (https://github.com/borodust/cl-bodge/commit/66557b9b01c0f5ecffb4df9bede86ad2a8ed15cf).
To install testing dist:
```
(ql-dist:install-dist "http://bodge.borodust.org/dist/org.borodust.bodge.testing.txt")
```
It can totally coexist with the stable one from README.
