### ISSUE TITLE
Installation issue:"The function BORDEAUX-THREADS::MAKE-SEMAPHORE is undefined."

### ISSUE THREAD

**Issue by olegharput** [borodust/trivial-gamekit#61]
or sometimes
installation issue:"COMPILE-FILE-ERROR while compiling #<CL-SOURCE-FILE "log4cl" "watcher" "watcher">"

What must i do?

**Comment by borodust** [comment]
First, you must ensure you are using latest quicklisp distribution and supported Common Lisp implementation.
Supported implementations are 64bit SBCL and CCL. Make sure you are using recent versions. 
To update quicklisp repo invoke:
```common-lisp
(ql:update-all-dists)
```
Try loading `trivial-gamekit` after this.
If you still have problems, please, provide additional invormation:
- Your Common Lisp implementation and its version
```common-lisp
(list (lisp-implementation-type) (lisp-implementation-version))
``` 
- Where is your `bordeaux-threads` system
```common-lisp
(ql:where-is-system :bordeaux-threads)
```

**Comment by olegharput** [comment]
i tried them all but another issue:
=>"COMPILE-FILE-ERROR while compiling #<CL-SOURCE-FILE "log4cl" "watcher" "watcher">"
my infos:
1) =>("SBCL" "1.4.5.debian")
2) => #P"/usr/share/common-lisp/source/bordeaux-threads/"

**Comment by borodust** [comment]
From the looks of it, you are using debian packages to get common lisp systems. Don't do that - systems in those packages are heavily outdated. SBCL is old too.

As a beginner, try Portacle instead: https://portacle.github.io/ (https://github.com/portacle/portacle/releases/download/1.4/lin-portacle.tar.xz)

**Comment by borodust** [comment]
Feel free to reopen if you have more questions regarding `trivial-gamekit` loading procedure.
