### ISSUE TITLE
[feature request] bind-scroll-wheel

### ISSUE THREAD

**Issue by AkashaP** [borodust/trivial-gamekit#65]
I would like callback handlers for scrolling up and down, which doesn't seem to be caught by bind-any-button.
this library is looking really sweet c:

**Comment by AkashaP** [comment]
im closing this issue since i have a fix, other people can use the patch if they want to

**Comment by borodust** [comment]
Patch looks good. Can you, please, make a PR?

**Comment by AkashaP** [comment]
sure thing!
